"""Add icon field to Championship

Revision ID: b5e4fd73a55f
Revises: dd0d3150792a
Create Date: 2025-05-12 15:17:40.673146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e4fd73a55f'
down_revision = 'dd0d3150792a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('championship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('championship', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
